name: SSH Execute Command

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Test port 22 with nc
      run: nc -zv ${{ secrets.SSH_REMOTE_HOST }} 22

  ssh-job:
    runs-on: ubuntu-latest

    steps:
    - name: Execute command on remote server via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/www/dashou-dot-dev && git pull origin main;
          echo ${{ secrets.ROOT_PASSWD }} | sudo -S systemctl restart dashou-dot-dev
