name: Deploy to Host
on:
  push:
    branches:
      - main # Triggers when push on main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_SECRET_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_SECRET_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key

      - name: Pull code to server with SSH
        run: ssh -i $SSH_KEY_PATH -vvv -o StrictHostKeyChecking=no server@${{ secrets.HOST_IP }} 'cd ~/www/dashou-dot-dev && git pull origin main; npm install; echo ${{ secrets.ROOT_PASSWD }} | sudo -S systemctl restart dashou-dot-dev'
